### ISSUE TITLE
Training time and machine configuration

### ISSUE THREAD

**Issue by Snnzhao** [DevinJake/NS-CQA#26]
Thanks for publishing such outstanding work.
I train your model on google colab(gpu Tesla P100 16Gmemory, Xeon CPU@2.30GHz,1core) with the KG server run on local computer (64g memory, i9 12core, flask multi thread).
The training is too slow, about over 24hrs an epoch.
I do not know why this happends.
It will help a lot if you can tell me youre machine configuration

**Comment by DevinJake** [comment]
Hi, Snnzhao, thank you for noticing our work.
Actually, since we employed RL in the training, most of the time consumed in the training process is the time that we searched for the triples in the KG server and computed the rewards.
That means the bottleneck of the training time is the I/O time, i.e., the knowledge base query time and the network transfer time.
We established the webserver and the GPU server in the same local network and therefore reduce the I/O time a lot. 
However, when computing the reward, we still need to retrieve the relevant triples in the huge KG, conduct reasoning, predict answers, and calculate the reward to train the model by using the RL paradigm, which will inevitably cost some time.
That's why the training time is much more than the conventional end-to-end models.
In our experiment environment, an epoch will consume 4~6 hours.
We have re-implement the previous work, such as CIPITR, and took over one month to finish training the model. 
Cheers!

**Comment by Snnzhao** [comment]
Hi, DevinJake. Thanks for your help. If I train with i7 8cores, 2070Maxq laptop under the same local networks. Will it be enough for trainning? If not, what machine configuration should be enough.

**Comment by DevinJake** [comment]
> Hi, DevinJake. Thanks for your help. If I train with i7 8cores, 2070Maxq laptop under the same local networks. Will it be enough for trainning? If not, what machine configuration should be enough.

If you are using the laptop, that will cost more time.
The configuration of my laptop is i7-9750 2.6GHz, 8 cores, RTX 2070.
Compared with the GPU server in our lab, which consists of RTX 2080, the training on my laptop is much slower.
Approximately it will take twice as much time as the GPU server to train.
The GPU on your laptop is actually enough to train the model, however, it is not devoted to deep learning.
I think you could have a try on your laptop. You could train the model and the time would not be that bad.
But I still recommend you to configure the experiment environment on the GPU server, if possible.
Good luck, cheers!

**Comment by Snnzhao** [comment]
Thanks.
