### ISSUE TITLE
The difference of the defined action betweent CSQA and WebqustionsSP

### ISSUE THREAD

**Issue by Snnzhao** [DevinJake/NS-CQA#39]
I found the actions (A1~A10 for example) are different between CSQA and WebqustionsSP experiment.
And I am puzzled by this. Can the actions be generally defined?

**Comment by DevinJake** [comment]
> I found the actions (A1~A10 for example) are different between CSQA and WebqustionsSP experiment.
> And I am puzzled by this. Can the actions be generally defined?

Hi, Snnzhao:

Since the format of the questions between CSQA and WEBSP are different, we designed different sets of actions for the two datasets. 
Actually, in order to utilize the annotations (the logic forms that the dataset has provided) in WEBSP, we randomly selected some samples from the training dataset and found a way to transform the annotations into the corresponding actions and used these actions as the supervision signals to pre-train the model to solve the cold-start problem in RL.
Under such circumstances, we designed the actions in WEBSP following the format of the provided annotations. 

Yes, we could totally use the same sets of actions in both datasets, however in that way, in the WEBSP dataset, we have to found the actions in a brute-force way, like what we did in CSQA, to pre-train the model. 
We consider that unnecessary since that will waste the provided annotations in WEBSP and also consume a lot of time.

In the future, we will define a more general set of actions to satisfy both datasets, and that would be interesting.
Cheers!

**Comment by Snnzhao** [comment]
I am quite interesting with the result on webquestionSP when using the same brute-force pretrainning way as CSQA instead of using the annotations.
And will it cost a lot of time to find the pseudo actions?
I want to run this experiment to see what will happen.
It will help a lot if you can provide the code for the BFS algorithm?

**Comment by DevinJake** [comment]
> I am quite interesting with the result on webquestionSP when using the same brute-force pretrainning way as CSQA instead of using the annotations.
> And will it cost a lot of time to find the pseudo actions?
> I want to run this experiment to see what will happen.
> It will help a lot if you can provide the code for the BFS algorithm?

Hi, Snnzhao:

That's a very interesting idea.
Yes, it will cost some time to find the pseudo-gold annotations by using BFS, however, it is worth trying.
We have updated the relevant code and README for BFS in CQA.
Please refer to '3. Training the neural generator' in the CQA section in the README to see our explanation.

Unfortunately, we haven't tried to search for pseudo-gold annotations in webquestionSP by using BFS.
We only tried to transform the provided annotations into actions. 
If possible, you could try to search for them by adapting our BFS code used in the CQA dataset.
We are sorry for that.

Also, we have uploaded the NSM code in our EMNLP project, which is: https://github.com/DevinJake/MRL-CQA/blob/master/S2SRL/train_scst_nsm.py.
If you are urgent to see the NSM code, please refer to it to see whether it could solve your problem or not.

Cheers!

**Comment by Snnzhao** [comment]
Thanks a lot for your patience and reply, that really helps  a lot.
Best wishes
