### ISSUE TITLE
Difference between the code and the paper of NSM

### ISSUE THREAD

**Issue by Leext** [DevinJake/NS-CQA#43]
I read the implementation of NSM in https://github.com/DevinJake/MRL-CQA/blob/master/S2SRL/train_scst_nsm.py. I find that the code is different from the original paper. 
In the original paper, the decoder generates tokens using structures like Pointer Network with variable vocabulary provided by _Computer_ module. In your code the decoding vocabulary is fixed. The decoder dose not query KB during the decoding process whereas in the original paper, the decoder executes a query once it is generated and saves results in memory.
It seems that your implementation is a hybrid with NS-CQA generative model structure and NSM training method.
I am not pretty sure. There might be some misunderstandings. 
I wonder if the code is different from the NSM paper.

**Comment by DevinJake** [comment]
> I read the implementation of NSM in https://github.com/DevinJake/MRL-CQA/blob/master/S2SRL/train_scst_nsm.py. I find that the code is different from the original paper.
> In the original paper, the decoder generates tokens using structures like Pointer Network with variable vocabulary provided by _Computer_ module. In your code the decoding vocabulary is fixed. The decoder dose not query KB during the decoding process whereas in the original paper, the decoder executes a query once it is generated and saves results in memory.
> It seems that your implementation is a hybrid with NS-CQA generative model structure and NSM training method.
> I am not pretty sure. There might be some misunderstandings.
> I wonder if the code is different from the NSM paper.

Hi, Leext:

You have made a very clear understanding of what we have done in the re-implementation of NSM.
In the EMNLP paper, we said:
'As the code of NSM (Liang et al., 2017) has not been made available, we re-implemented it and incorporated our programmer to predict programs, and employed the reinforcement learning settings in NSM to optimize the programmer.'

Since the length of the paper is limited, we could not explain it thoroughly.
Actually, in our another paper, we have explained it as:
Since the primitive actions are designed in a different way, '...unlike NSM, we do not refer to the intermediate variables when generating the tokens of a trial. Therefore it is unnecessary to incorporate the key-variable memory, which is used to maintain and refer to intermediate program variables in our work. We thus removed the key-variable memory component in the seq2seq model in our reimplementation of NSM.'

Yes, as you mentioned, our code is different from the NSM paper.
Cheers!
